### PR TITLE
Dockerfile refactored a little and updated to v3 of Nexus

### PR DESCRIPTION
**Pull request by IronicBadger**
Refactored the download RUN command to support the new directory structure used in the milestone release for v3.

[Review on Reviewable](https://reviewable.io/reviews/sonatype/docker-nexus/15)

### CODE REVIEW

**Comment by jswank** [comment]
Thanks for the PR.

We have been testing a docker image based on NX3 Milestone 5, and there are several more changes required than the ones in this PR.  My intent is to publish it this week.

**Comment by ChristianUlbrich** [comment]
@jswank Any update on this? I'd like to test the current Milestone 7 Release and ideally I would like to run it dockerized...

**Comment by jswank** [comment]
My understanding is that the nexus team is taking on work around providing
a docker container.  In the meantime, something like `jswank/nexus3` is
more appropriate for Nexus 3: note this was for m6 and, at the very least,
line 36 is not required for m7.

https://github.com/jswank/dockerfiles/blob/master/nexus3/Dockerfile

**Comment by kellyrob99** [comment]
@ChristianUlbrich Sorry for the late response, we've started another repository to handle images for NX3
https://github.com/sonatype/docker-nexus3

**Pull request closed without merging**
